### ISSUE TITLE
/web_modules/rxjs/operators.js HTTP/1.1" 404

### ISSUE THREAD

**Issue by gbishop** [simonhorlick/pika-react-example#1]
I'm trying your example and getting a 404 on operators.js. My web_modules folder has

rxjs--operators.js instead of rxjs/operators.js

I realize this may be a moving target. Has something changed? Or am I doing something wrong?

I'm running things just the way you suggested.

**Comment by simonhorlick** [comment]
It looks like I had an old version of @pika/web in the package.json. I’ve updated it to latest so the paths are correct now!
